// Managed `.opencode/opencode.jsonc` scaffolding for Ninthwave agents.
//
// Background: the previous auto-approval workaround exported
// `OPENCODE_PERMISSION='{"$schema":"...","permission":"allow"}'` at worker
// launch time. Upstream opencode parses that env var and deep-merges it
// directly into `result.permission`, so the value must be a Permission VALUE
// (string action or per-tool object), not a full config-file shape. The old
// payload silently did nothing, which is why opencode workers kept asking
// for permission.
//
// Fix: at `nw init` time, write (or merge into) a project-level
// `.opencode/opencode.jsonc` that sets per-agent permissions for every
// Ninthwave-orchestrated agent. Per-agent scoping means user-initiated
// opencode sessions are unaffected; only our named agents get blanket
// auto-approval.
//
// Precedence: `.opencode/opencode.jsonc` sits in opencode's config-dir layer,
// which is higher precedence than project-root `opencode.json` and the user's
// global `~/.config/opencode/` config, so this takes priority without
// touching files the user may have committed.

import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "fs";
import { dirname, join } from "path";

/** Canonical Ninthwave-orchestrated opencode agent names. */
export const NINTHWAVE_OPENCODE_AGENT_NAMES = [
  "ninthwave-implementer",
  "ninthwave-reviewer",
  "ninthwave-rebaser",
  "ninthwave-forward-fixer",
] as const;

/**
 * Explicit per-tool "allow" map covering every known opencode tool key.
 *
 * We enumerate rather than using the `"allow"` string shorthand or a
 * speculative `{"*":{"*":"allow"}}` wildcard form because:
 *
 *   1. The upstream schema is `.catchall(PermissionRule)` with no documented
 *      wildcard semantics for `"*"` as a key.
 *   2. Explicit leaves deep-merge correctly against any partial
 *      `agent.<name>.permission` a user may have set (per-tool leaves win).
 *   3. Adding a future tool key upstream that defaults to `"ask"` is a
 *      one-line change here; over-enumeration is safe because unknown keys
 *      fall through the catchall.
 */
export const NINTHWAVE_OPENCODE_ALLOW_ALL_PERMISSION: Readonly<
  Record<string, "allow">
> = {
  edit: "allow",
  bash: "allow",
  webfetch: "allow",
  websearch: "allow",
  task: "allow",
  skill: "allow",
  external_directory: "allow",
  question: "allow",
  read: "allow",
  glob: "allow",
  grep: "allow",
  list: "allow",
  lsp: "allow",
  todowrite: "allow",
  codesearch: "allow",
  doom_loop: "allow",
};

/** Result of a seed pass. */
export interface SeedOpencodeConfigResult {
  /** Absolute path of the managed file. */
  path: string;
  /** What we did: created a fresh file, merged into an existing one, or left it alone. */
  action: "created" | "merged" | "unchanged";
}

/** Dependencies for seedOpencodeConfig, injectable for testing. */
export interface SeedOpencodeConfigDeps {
  existsSync: typeof existsSync;
  mkdirSync: typeof mkdirSync;
  readFileSync: typeof readFileSync;
  writeFileSync: typeof writeFileSync;
}

const defaultDeps: SeedOpencodeConfigDeps = {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
};

const MANAGED_HEADER = [
  "// Managed by ninthwave. Sets auto-approval for ninthwave-orchestrated",
  "// agents so worker sessions do not pause for permission prompts.",
  "// Other agents and manual opencode sessions are unaffected.",
  "//",
  "// Regenerated by `nw init`. Non-agent keys you add to this file are",
  "// preserved; keys under `agent.ninthwave-*.permission` are managed.",
].join("\n");

const SCHEMA_URL = "https://opencode.ai/config.json";

/**
 * Strip line and block comments from a JSONC document so it can be parsed
 * with `JSON.parse`. This is intentionally lightweight: it handles the
 * comment styles opencode's docs recommend (`//` and `/* *\/`) without
 * pulling in a full JSONC parser. String contents are preserved verbatim.
 */
export function stripJsoncComments(input: string): string {
  let out = "";
  let i = 0;
  const n = input.length;
  let inString = false;
  let stringQuote = "";

  while (i < n) {
    const ch = input[i]!;
    const next = i + 1 < n ? input[i + 1]! : "";

    if (inString) {
      out += ch;
      if (ch === "\\" && i + 1 < n) {
        out += input[i + 1]!;
        i += 2;
        continue;
      }
      if (ch === stringQuote) {
        inString = false;
      }
      i += 1;
      continue;
    }

    if (ch === '"' || ch === "'") {
      inString = true;
      stringQuote = ch;
      out += ch;
      i += 1;
      continue;
    }

    if (ch === "/" && next === "/") {
      // Line comment: skip until newline (keep the newline).
      i += 2;
      while (i < n && input[i] !== "\n") i += 1;
      continue;
    }

    if (ch === "/" && next === "*") {
      // Block comment: skip until closing */ (do not emit).
      i += 2;
      while (i < n && !(input[i] === "*" && input[i + 1] === "/")) i += 1;
      i += 2;
      continue;
    }

    out += ch;
    i += 1;
  }

  return out;
}

type JsonObject = Record<string, unknown>;

function isPlainObject(value: unknown): value is JsonObject {
  return (
    typeof value === "object" &&
    value !== null &&
    !Array.isArray(value)
  );
}

/**
 * Build a Ninthwave-managed permission block for one agent, merging over any
 * existing agent entry the user may have set. We only force the permission
 * leaves we own; sibling Agent fields (model, prompt, temperature, etc.) are
 * preserved, and any extra permission keys the user set are kept unless
 * they collide with ours.
 */
function mergeAgentPermission(existing: unknown): JsonObject {
  const base: JsonObject = isPlainObject(existing) ? { ...existing } : {};
  const existingPermission = isPlainObject(base["permission"])
    ? (base["permission"] as JsonObject)
    : {};
  base["permission"] = {
    ...existingPermission,
    ...NINTHWAVE_OPENCODE_ALLOW_ALL_PERMISSION,
  };
  return base;
}

/**
 * Produce the managed config object for a fresh write -- all four agents
 * with full auto-approval and a `$schema` hint.
 */
function freshManagedConfig(): JsonObject {
  const agents: JsonObject = {};
  for (const name of NINTHWAVE_OPENCODE_AGENT_NAMES) {
    agents[name] = { permission: { ...NINTHWAVE_OPENCODE_ALLOW_ALL_PERMISSION } };
  }
  return {
    $schema: SCHEMA_URL,
    agent: agents,
  };
}

/**
 * Merge Ninthwave's managed agent permissions into an existing parsed
 * config object, preserving every other user key verbatim.
 */
function mergeManagedConfig(existing: JsonObject): JsonObject {
  const next: JsonObject = { ...existing };
  const agent: JsonObject = isPlainObject(next["agent"])
    ? { ...(next["agent"] as JsonObject) }
    : {};
  for (const name of NINTHWAVE_OPENCODE_AGENT_NAMES) {
    agent[name] = mergeAgentPermission(agent[name]);
  }
  next["agent"] = agent;
  return next;
}

/**
 * Serialise the managed config with the managed header comment. Both the
 * fresh-create and merge paths use the same format so a second `nw init`
 * against a file we previously wrote is a true no-op: parse, deep-equal,
 * short-circuit as "unchanged".
 */
function serialise(config: JsonObject): string {
  return `${MANAGED_HEADER}\n${JSON.stringify(config, null, 2)}\n`;
}

/** Structural deep-equality for plain JSON values. */
function deepEqual(a: unknown, b: unknown): boolean {
  if (a === b) return true;
  if (typeof a !== typeof b) return false;
  if (Array.isArray(a)) {
    if (!Array.isArray(b) || a.length !== b.length) return false;
    for (let i = 0; i < a.length; i += 1) {
      if (!deepEqual(a[i], b[i])) return false;
    }
    return true;
  }
  if (isPlainObject(a) && isPlainObject(b)) {
    const keysA = Object.keys(a);
    const keysB = Object.keys(b);
    if (keysA.length !== keysB.length) return false;
    for (const key of keysA) {
      if (!deepEqual(a[key], b[key])) return false;
    }
    return true;
  }
  return false;
}

/**
 * Create or merge `.opencode/opencode.jsonc` at the given project root.
 *
 * - Creates a fresh managed file when none exists.
 * - Merges Ninthwave's managed `agent.ninthwave-*.permission` leaves into an
 *   existing file, preserving everything else the user wrote.
 * - Returns `"unchanged"` when the on-disk file already matches the merge
 *   result, so repeated `nw init` runs are idempotent.
 */
export function seedOpencodeConfig(
  projectDir: string,
  deps: SeedOpencodeConfigDeps = defaultDeps,
): SeedOpencodeConfigResult {
  const targetPath = join(projectDir, ".opencode", "opencode.jsonc");
  const targetDir = dirname(targetPath);
  if (!deps.existsSync(targetDir)) {
    deps.mkdirSync(targetDir, { recursive: true });
  }

  if (!deps.existsSync(targetPath)) {
    deps.writeFileSync(targetPath, serialise(freshManagedConfig()));
    return { path: targetPath, action: "created" };
  }

  const raw = deps.readFileSync(targetPath, "utf-8") as string;
  let parsed: JsonObject;
  try {
    const stripped = stripJsoncComments(raw);
    const trimmed = stripped.trim();
    const value = trimmed.length === 0 ? {} : JSON.parse(trimmed);
    parsed = isPlainObject(value) ? value : {};
  } catch {
    // The user's file is not valid JSONC. Rather than clobber it, leave
    // it alone and surface the problem by returning "unchanged". The init
    // summary will still include the path, and users can fix the syntax
    // and re-run.
    return { path: targetPath, action: "unchanged" };
  }

  const merged = mergeManagedConfig(parsed);
  if (deepEqual(merged, parsed)) {
    return { path: targetPath, action: "unchanged" };
  }
  deps.writeFileSync(targetPath, serialise(merged));
  return { path: targetPath, action: "merged" };
}
